export const actionType = {
  INPUT_CHANGE: "INPUT_CHANGE",
  RESET_VALUE: "RESET_VALUE",
  ADD_TODO: "ADD_TODO",
  GET_TODO_LIST: "GET_TODO_LIST",
  DELETE_TODO: "DELETE_TODO",
  SET_TODO: "SET_TODO",
  EDIT_TODO: "EDIT_TODO",
};
